site_name: AI for the SDLC 
repo_url: https://code-dot-mil.github.io/AI4SDLC/  # Update with your actual repo.  <--this will need to change
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/fulcrum_seal.png
  favicon: images/fulcrum_seal.png  
  include_homepage_in_sidebar: False
  palette:
    scheme: default  # Options: default (light) or slate (dark mode)
    primary: blue
    accent: deep-orange
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.highlight
markdown_extensions:
  - footnotes

nav:
  - Home:
    - Overview: index.md
    - Toolchain Fundamentals: plays/fundamentals-play.md
  - Plays:
    - Toolchain Fundamentals: plays/fundamentals-play.md
  - Tools & Templates:
    - Play Template: resources/template.md
    - Architectural Decision Records: resources/ArchitecturalDecisionRecord.md
  - Reference:
     - Glossary: glossary.md

plugins:
  - search
