site_name: AI for the SDLC 
repo_url: https://github.com/Code-dot-mil/AI4SDLC 
repo_name: "View Repository"
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides/
  font:
    text: Source Sans Pro
  logo: images/Seal-DoDCIO-Fulcrum_large.png
  favicon: images/Seal-DoDCIO-Fulcrum_small.png 
  include_homepage_in_sidebar: False
  palette:
    scheme: default  # Options: default (light) or slate (dark mode)
    primary: blue
    accent: pink
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.highlight
markdown_extensions:
  - footnotes

nav:
  - Home:
    - Overview: index.md
    - Guidance Lifecycle: lifecycle.md
  - Plays:
    - Toolchain Fundamentals: plays/fundamentals-play.md
    - Code Generation & Completion: plays/code-gen-play.md
    - AI-Autonomy continuum: plays/ai-autonomy_continuum_play.md
  - Patterns:
      - Human-Machine Interaction Patterns: plays/human-machine-patterns.md
  - Tools & Templates:
    - Play Template: resources/template.md
    - Architectural Decision Records: resources/ArchitecturalDecisionRecord.md
  - Reference:
     - Glossary: glossary.md

extra_css:
  - stylesheets/wordwrap.css
  - stylesheets/extra.css

plugins:
  - search
  # - awesome-pages  # Enables structured navigation
